import { Info } from "lucide-react"

export default function Credits() {
  return (
    <div className="text-gray-200 text-sm space-y-3">
      <div className="flex items-center gap-2 text-xl font-semibold">
        <Info className="h-5 w-5" />
        <span>Credits</span>
      </div>
      <p>
        Game inspired by{' '}
        <a
          href="https://contexto.me"
          target="_blank"
          rel="noopener noreferrer"
        >
          Contexto
        </a>.
      </p>
      <p>
        All synonyms are generated by{' '}
        <a
          href="https://groq.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Groq's AI model
        </a>.
      </p>
      <p>
        Developer Note: Thanks for playing! If you enjoyed the game, do consider{' '}
        <a
          href="https://www.buymeacoffee.com/itsjunsheng"
          target="_blank"
          rel="noopener noreferrer"
        >
          buying me a coffee
        </a>
        ! :D
      </p>
      <p className="text-xs text-gray-400 italic pt-2">
        © {new Date().getFullYear()} junsheng. All rights reserved.
      </p>
    </div>
  )
}
