import { Lightbulb } from "lucide-react"

export default function Instructions() {
  return (
    <div className="pb-2 text-gray-200 text-sm space-y-4">
      <div className="flex items-center gap-2 text-xl font-semibold">
        <Lightbulb className="h-5 w-5" />
        <span>How to Play</span>
      </div>
        <p>
          Guess the hidden word.
        </p> 
        <p>
          Each round, you will be given a synonym generated by Artificial Intelligence (AI).
        </p> 
        <p>
          You have unlimited attempts. Challenge yourself to guess the word in the fewest rounds and shortest time possible.
        </p> 
        <p>
           Note that AI-generated synonyms may occasionally be inaccurate
        </p>
    </div>
  )
}
